# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  #name: 'default'
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  solution: 'cine.sln'
  angularDirectory: 'AngularApp'

steps:
- script: |
    npm install -g @angular/cli
    npm install --save-dev @angular-devkit/build-angular
    npm install
    ng build --prod
  displayName: 'npm install & ng build'
  workingDirectory: '$(angularDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.BuildId).zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(6b046a51-8f67-4253-b7de-78eea66e9f0d)'
    appType: 'webApp'
    WebAppName: 'CinephiliacsFE'
    packageForLinux: '$(Build.BuildId).zip'